	,"gentoo/EUMM-RUNPATH - https://bugs.gentoo.org/105054 cpan/ExtUtils-MakeMaker: drop $PORTAGE_TMPDIR from LD_RUN_PATH"
	,"gentoo/EUMM_delete_packlist - Don't install .packlist or perllocal.pod for perl or vendor"
	,"gentoo/config_over - Remove -rpath and append LDFLAGS to lddlflags"
	,"gentoo/cpan_definstalldirs - Provide a sensible INSTALLDIRS default for modules installed from CPAN."
	,"gentoo/cpanplus_definstalldirs - Configure CPANPLUS to use the site directories by default."
	,"gentoo/create_libperl_soname - https://bugs.gentoo.org/286840 Set libperl soname"
	,"gentoo/drop_fstack_protector - https://bugs.gentoo.org/348557 Don't force -fstack-protector on everyone."
	,"gentoo/enc2xs - Tweak enc2xs to follow symlinks and ignore missing @INC directories."
	,"gentoo/mod_paths - Add /etc/perl to @INC"
	,"gentoo/patchlevel - List packaged patches for perl-5.18.2-r1(#2) in patchlevel.h"
	,"gentoo/aix_soname - aix gcc detection and shared library soname support"
	,"gentoo/opensolars_headers - Add headers for opensolaris"
	,"gentoo/cleanup-paths - Cleanup PATH and shrpenv"
	,"gentoo/usr_local - Remove /usr/local paths"
	,"gentoo/hints_hpux - Fix hpux hints"
	,"gentoo/darwin-cc-ld - https://bugs.gentoo.org/297751 darwin: Use $CC to link"
	,"gentoo/interix - Fix interix hints"
	,"fixes/net_smtp_docs - [rt.cpan.org #36038] Document the Net::SMTP 'Port' option"
	,"debian/cpan-missing-site-dirs - Fix CPAN::FirstTime defaults with nonexisting site dirs if a parent is writable"
	,"fixes/memoize_storable_nstore - [rt.cpan.org #77790] Memoize::Storable: respect 'nstore' option not respected"
	,"fixes/net_ftp_failed_command - [rt.cpan.org #37700] Net::FTP: cope gracefully with a failed command"
	,"fixes/perlbug-patchlist - [3541c11] [perl #118433] Make perlbug look up the list of local patches at run time"
	,"fixes/module_metadata_taint_fix - [bff978f] [rt.cpan.org #88576] untaint version, if needed, in Module::Metadata"
	,"fixes/IPC-SysV-spelling - [rt.cpan.org #86736] Fix spelling of IPC_CREAT in IPC-SysV documentation"
	,"fixes/freemint -"
