Using gcc-config info in @ROOT@/
 [1] avr-4.5.3 *

 [2] powerpc64-unknown-linux-gnu-4.5.3 *

 [3] sh4-unknown-linux-gnu-4.5.3 *

 [4] x86_64-pc-linux-gnu-4.6.0
 [5] x86_64-pc-linux-gnu-4.6.1 *
 [6] x86_64-pc-linux-gnu-4.6.2
Using gcc-config info in @ROOT@/./
 [1] avr-4.5.3 *

 [2] powerpc64-unknown-linux-gnu-4.5.3 *

 [3] sh4-unknown-linux-gnu-4.5.3 *

 [4] x86_64-pc-linux-gnu-4.6.0
 [5] x86_64-pc-linux-gnu-4.6.1 *
 [6] x86_64-pc-linux-gnu-4.6.2
