#! /bin/sh
case `uname` in
Linux*)	;;
*)	echo Probably not on a Linux system 1>&2
	exit 1;;
esac
set -v
python$EXE ../../Tools/scripts/h2py.py -i '(u_long)' /usr/include/sys/types.h /usr/include/netinet/in.h /usr/include/dlfcn.h /usr/include/linux/cdrom.h
